
Namespace(root_path='kits19/data', list_dir='./lists_kits19', dataset='KiTS19', num_classes=3, max_iterations=30000, max_epochs=150, batch_size=4, n_gpu=1, deterministic=1, base_lr=0.01, img_size=224, seed=1234, n_skip=3, vit_name='R50-ViT-B_16', vit_patches_size=16, checkpoint_dir='./checkpoints_kits19', use_attention=0, exp='TU_KiTS19_224')
  0%|                                       | 0/30000 [00:42<?, ?it/s]
Traceback (most recent call last):
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/train.py", line 86, in <module>
    trainer_kits19(args, net)
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/trainer.py", line 269, in trainer_kits19
    for sampled_batch in train_loader:
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 626, in __next__
    with torch.autograd.profiler.record_function(self._profile_name):
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/autograd/profiler.py", line 648, in __exit__
    torch.ops.profiler._record_function_exit._RecordFunction(record)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/_ops.py", line 670, in __getattr__
    op_, op_dk_, tags = torch._C._get_operation_overload(
KeyboardInterrupt