
Namespace(root_path='kits19/data', list_dir='./lists_kits19', dataset='KiTS19', num_classes=3, max_iterations=30000, max_epochs=150, batch_size=4, n_gpu=1, deterministic=1, base_lr=0.0001, img_size=224, seed=42, n_skip=3, vit_name='R50-ViT-B_16', vit_patches_size=16, checkpoint_dir='./checkpoints_kits19', use_attention=0, exp='TU_KiTS19_224')
  0%|                                       | 0/30000 [00:00<?, ?it/s]/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in DivBackward0. Traceback of forward call that caused the error:
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/train.py", line 86, in <module>
    trainer_kits19(args, net)
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/trainer.py", line 223, in trainer_kits19
    loss, ce_loss, dice_loss = criterion(outputs, label_batch)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/trainer.py", line 29, in forward
    dice_loss = self.dice_loss(inputs, targets, softmax=softmax)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/utils.py", line 42, in forward
    dice = self._dice_loss(inputs[:, i], target[:, i])
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/utils.py", line 28, in _dice_loss
    loss = (2 * intersect + smooth) / (z_sum + y_sum + smooth)
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  0%|                                       | 0/30000 [01:10<?, ?it/s]
Traceback (most recent call last):
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/train.py", line 86, in <module>
    trainer_kits19(args, net)
  File "/home/hous/Desktop/Kidney_Segmentation/TransUNet/trainer.py", line 226, in trainer_kits19
    loss.backward()
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/hous/anaconda3/envs/torch/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'DivBackward0' returned nan values in its 0th output.